const store = {
  "pBWofIvxGamAR1SQMFA5JAwh6kaDvvEeL9SkBc7EccPnwIoadOM4ipj5e7K+rWqI": "Alchemist's Fire Single Use Range 3 Upgrade",
  "9ZUORwqq9Oh1V+FVWSBVNpGOSiUOIZRzdENNaMQiaqCKNaQaDm7pGGkWeX8K1e5+": "Climbing Kit Range 1 Upgrade",
  "xWRqZOC0cotFDMT7bOlNrlalJadzqkpyQzFpeanIj01FQQy5LWI6V1mY2qMk+U0j": "Cloak of Shadows Disengage 2 Upgrade",
  "jzlYDUlIfYvi0Ou/ftZxDTnyD/Umj2TD20fv45VKxQAZeuXEXF6nVQs97TyHz0gA": "Feather Boots 2 Upgrade",
  "nDiHgagbsPHuLe02iV+WtFWmY23Fxd0aVTTzR8pTWPR0q61BPopBkvEDRat+mIQc": "Health Potion Single Use 2 Upgrade",
  "0tQklhHgrys5Gfl4X8vEwOPCwk4Z4BQrlx9aVEI5ACDkyGjBFw6VkppIACFqtU8s": "Magic Ring Single Use Dodge 1 Upgrade",
  "X7r7lV5GomKKwgG4r4qWg95Smx1jCF7a0JmVZiogIwMVmlW1RbjYXGoFErNjtkDI": "Magic Weapon 4 Upgrade",
  "hMBYeUCW0wk6U2lE8Q7yNeUZLaRuCoPAoR8pWWlJz8ZlIWr/WfeGSNiyIylQV19P": "Raven Broach Single Use 1 Upgrade",
  "NeXfTv1EljFTzutEhk3gFNBIEG7a2j58/h0Pnz2kA4O9qjae1KKFkkCJ5e3nB0cY": "Sling and Stone Range 2 Upgrade",
  "A5OblCliRoKP9fRRpEREAQeErmOOlIroTsOzNHIRSLgUsKtRJwtdoKoZGugbyYWu": "Stonekin Serum Single Use 2 Upgrade",
  "A+nA1sahKwhWAAtq/ehgM7vhQR2qoFug0ZkLcC55NVnqd5/6b1uHD8d+Fd0Gnh5u": "Eel Sorcerer Poison Range Beam Deep Wizard 23 Adversary Character",
  "N6oU33NuzZIFY6IjICdy/dZX7izbM3SEtM+50xRZoEaV36+kR+0nsRqq1HCUgALG": "Shark Warrior Deadly Deep Knight 23 Adversary Character",
  "K6R2hXpNpI9cQ2JtXFzh4d7cooeSac60R5NpReHoN3r97h1bPXePPiNd68fIOw92": "Cleaner Crab Deep Heal Recover 3 Upgrade",
  "N+Ag/y3InT8HXbsXreMux7k6DRqH9vCdeCXFGOmChnFDOEJtyhlWuxf/EKrTMism": "Consult the Eyes Deep Spell Reroll Range 2 Upgrade",
  "HMkZJgq2z2dswQikO3zsfTB2lpIL+cGt4EYDSSmaKDk8moKqs0DQgMiImQyZJqtS": "Electroception Glands Deep Two Uses Reroll 2 Upgrade",
  "YimU2GmSUrhlR2PVKshlUllPkk9Gik2ojUAyGMql1DMezJOBI6R2hXpNpI9cT6TK": "Ink Shroud Deep Single Use Dodge 2 Upgrade",
  "ySGIhkNhVmliQNqex6pFgNu0qo8kno0Ui1EakHYjFqdg1p2FNxJHSO0K5ItVHqif": "Octopus Potion Single Use Range 1 Upgrade",
  "9l7j8iVvqiPSz21g38+sNBnDp1Es4mR9SoWQtu7u5IyQTOXriMPZ9tw+Ejv+P0mX": "The Anemone Blade Range Stun Relic",
  "cHGrdsAjt7e1Yz3gQF4vypc7h/4w5ePHyG6MiozAZRzgGRaemsP2a2VNNE9crphT": "Giblin Fishers Range Team Dodge Goblin 14 Adversary Character",
  "MLC3F/BIrk18sBVZpbCJexsf/22tdsE2Gm5wvHKkEXFbkGX1/jVGQIU8MUfQUu8z": "Mud Holes Goblin 2",
  "OWIywyjkmdti3ro1bNyrhy9Q4TMK/fxWgbXM6jDPp0aY9mjeqxOE564POQZ7j14B": "Pig Warlord Charge Pig Warlord Fighter 23 Adversary Character",
  "u0b4dBgwejS9fubKu+cuoIli9bgst3HrEb8+sOA309zB43AN5uzqx6sGmLTKIsAI": "Axe Pig Range Recover Pig 14 Adversary Character",
  "0JV1LT0xEaGQvfDyF48sYf8ckqXwsCIXKh7tOzG+bMX8SRsFeO7caq1Wvwx40nfx": "Raider Pig Range Pig Scout 16 Adversary Character",
  "mNjQ3h7e6EwNBIJKcKdyQdZAqMGjqAg8/omrBXwfh1jx+u3H+GjKysAh4RL1cnVC": "Shield Pig Recover 16 Adversary Character",
  "QVjp2+gQ886MJEsbI0R+uWLdGzR3d06NgRJuaWvFjFoIhG7FFFSiKig/2QSyGyrE": "Soldier Pig Range Recover 14 Adversary Character",
  "M4I/S/cYSqfRhFJkZ21F2+eg03VZoG+TRkBKToR25OLtyc7NCyflVUq1kHK35Yi2": "Banner of the Swinelord Warlord Tactics 1 Upgrade",
  "iSgMbWuMamNAQhCbSFZS/iFeQLi/eW4KnYiu/UWehtTf5ZxgnYclAZE3UbmbZk8N": "Shield Wall 2 Upgrade Armor",
  "+ULlUS/kWLwszcApHh4ZgxbTqePnuBrp06wtnVFSu/vqZRRSNtdT0oEjdPnUCpuH": "Brutal Charge Pig Beast 1 Upgrade",
  "gEKio9OHniOA4e+gOHj5+Wewmx21BWXiku12Gd22P8kIEoKatEdlahlmV8+PjHNf": "Cudgel Pig -2 Upgrade",
  "Qd0MIh0CCwPHj6FPadPq0NhKuzI5rXq4LIEsXhXawYnN084OpZDB6+AXD38oOrVz": "null",
  "GjRr80/FjfFf7bGkmXju1x8MgxWJqbw83FHtGxiZI4N2zwQEya+qXM4fSpkzHv5w": "Dark Wanderer Dodge Bone Darkness 23 Adversary Character",
  "kf+Hi6ihnBAWA+Q0RsAoJCHuPK7Yd4EhVfAEQIRK+3ao4VP/wAD++iuHHuKH5cMg": "Dark Watcher Range Dodge Bone Darkness 23 Adversary Character",
  "Pzl63G7Sc+MFToY9SAXujepSNev3mLIT9MRykXR6xfuQxuFSuBwESZ4UY7P5km8k": "Bone Stalker Range Move Armor Bone 12 Adversary Character",
  "B80l5/sNAovMuV8It9e71UoBftlE3da2DKuBHQ0lRHWnomFixbjZuPX8JAoYuR/X": "Bone Stalker Range Move Armor Bone 12 Adversary Character",
  "2r8VkcIZuFjEyRzySHqLdtWR8D+nflTfePxv8QaJA7NQdqtT5ycijjUoRxkgFQW1": "Bone Construct Range Bone 15 Adversary Character",
  "lZiPgDLUIPVyfW+G/eR6iVGstrkRaauIey0Ez1scSilRevpvaXLRlpEf2DLM4XDM": "Mark of Violence Darkness Deadly Magical 2 Upgrade",
  "ytuNIGebtC8iwIRDpOzKByZIrUeu54inCKST5S2vGAFnkS9Df58UYmxnBwdoadsw": "Bone Harvest Darkness Spell Health Range 3 Upgrade",
  "I0BDmcqyR5MfklU82VehoCrERNDgItmcymruI8aJVEPOUdBMkrRrNwIwoYSpUkVc": "Black Shroud Darkness Spell Armor Range 1 Upgrade",
  "ZnZuD4oUMcMRv0+Ag4OjvJFHtz/Y/iT0RGsCwOVPkBMnKgFjc/rnDcNa6LFSkhCK": "Dark Machination Darkness Tactic 5 Upgrade",
  "fvL/dMvpzoSI2w98hITcG+Xb/h/PkLjoAAnys6Khy9OrdHt46tUbFCRew7eAjtut": "Murder of Crows Darkness Two Uses Tactic Dodge 2 Upgrade",
  "NQSWiRc4KTAQlrIRxRMhDSju1OF7as25DjV/xLmkaD2rU5JoOxDInwk0YhmALZ6p": "Akadh Magician Range Wizard Goblin Small Rider 16 Neutral Character",
  "iaKgXkQnJ8eTnZOblYs3zlbdI0rFZ0uvNOMSvICNNlKmHezPdQHK0EuohE1pKEtL": "Magic Carpet Range  Small Medium Mount 10 Neutral Character",
  "yb0PD3R5UKFZl3QSw5QeAhU0REmcpRo/SgHBsgE1hIq2BaOIE3ZhHboNOx9E1PF8": "Water Elemental Construct Push Range Beam Elemental Empowered 20 Neutral Character",
  "8CjWVHT2qt+xpVNuv7Sow+2RvunDuNoCeP0bhzV9g5u7LRVEejwfuXgZjSr5c2WM": "Akadh Speargobs Range Recovery Team Shield Goblin 18 Neutral Character",
  "UWNofCaGZvKFEsI5/RuGs28iAp50bJWIUgc2dS9TWJzoyNpHRrLYn3MHMrxKggOE": "Elemental Core Wizard Construct Empower Spell 2 Upgrade",
  "ZOyBrkJsxorQqxXizXIKCh72hdF2V3lUdQEtbmu9cm+9WChqk4EneTJKlGrLiw+a": "Construct Battery Construct Empower Tactic 1 Upgrade",
  "CiB9nvQXh6Oqtuf03XsK0TsoDchBktqhD0YrkGURr6jtZ1UXZXeQQlYW2+e32yX7": "Goboverry Juice Single Use Range Move 1 Upgrade",
  "PRUq9P1rUm+mre1oIQnhqgjJCmCksqEGHkR7kPKtHPBAbjsVTShkkI0iIwnluFk0": "Born to Ride Mount 2 Upgrade",
  "qMqkhDRhfESupUa1lI4tooAlm9TNKM8r/1k2h3Sr9huAoJDVcgDr26nJbMXNegBS": "Disenchant Spell Wizard Range 1 Upgrade",
  "DZbx4IkmnxRY2cGJ/bSEnFKiQ07Lc4fNLbhJOrWQ8SOaGVZVw8E9LUsKS6MWyfug": "Chain Lightning Wizard Range 3 Upgrade",
  "GDUaFiJTi4eSL280f4+9xEaEgwXr8PRcC7jwgOi0ZCCsVSfIla0+SZGxuicYO66N": "Arboleth Sentinel Push Range Ally Shield Fighter 23 Advocate Character",
  "x48lwDDFq8PTq2RLMGtWFlacFqRmCAH05fuIqbD57j0ctAhEfFfRTCrQsgU7km9C": "Wild Elf Druid Range Nature Druid Transform Bind 26 Advocate Character",
  "H48CEcPXIEJ0+ewuVr1xEbn4jUNLJk00U+yK5VPA07tGjaBB9++hlc3TwElGfUhu": "Cave Bear Wild Elf Druid Beast Transform 0 Advocate Character",
  "fPSk7B3NQYA3/ui45dusLNzZ0fNCbiIz6HvEViTBS0dPSRmZ2DhJR0KNQ1kadQ4w": "Wild Elf Pathfinder Range Place Climb Nature Scout 21 Advocate Character",
  "iLinHQQEWdowoF38Ls2GehsR4yXQQYkB+KxkKLaNPCFWhkCO9qpoEEGc2XIhQAzS": "Brawler Bonus Die Tactic 2 Upgrade",
  "nAMJfIzzJsREwJ5ckok29D04XAK/Es2kUgWKiETRN3YMDKigI2LEjnAInuIPkXpT": "True Grid Recovery 2 Upgrade",
  "GUVb3cHBHg74vQkBAEBwbAy6cCPH394ekXBEO1kY75l8RAWempePLgLg7s248jx0": "Pendant Beast Single Use Damage Bonus 1 Upgrade",
  "HAKBPrNOBRoKFcI/2vJQYpV1MCEhHxzKmp/CDpHmsko97UMT62yKPQ+SB53BNdRi": "Bark Skin Druid Armor Range 2 Upgrade",
  "ZpwKNL02bXKP91xGkCrsV3hBDPmprKD5LusSYy6qmO8bVFHoXqLBnR0k7VZcSyTp": "Regrowth Nature Three Uses spell range recover health 3 upgrade",
  "CTgaegZyMinjk1FR+khaLruKYP17KIo9BxE3nMEx2vwTxdZiZSEpOQkJiI+Nh4jr": "wind walk nature spell place 2 upgrade",
  "h15w4T1qjduH4NLVq15r8nfT8efq9e48rVa2jcqCFOnDwJSyWOSKvmzXD95i20at": "moldorf bibliothecary range illusion wizard move place poson dodge 23 neutral character",
  "mdyHEhn40fhy/nzGF37pHtf2Hx71vxMEkwROtV88aInu1hbkLeEcluYdcrYSxCW6": "moldorf bibliothecary Illusory Horror Summon Upkeep Bind",
  "ETFi8VQuzxg3s4fOQoVq9dC0tLS/xx9iwqV6mqvE+Fss54+eY9+vXuhb0HDmLn9m": "moldorf hearthguard range shield fighter push 23 neutral character",
  "y8+fi9RqMB171FHXRr1ZAjHTKZRKYduxBkZUiuBKd1q1PIVAXq6prQMTBiQpRIKA": "moldorf shadowfoot range dodge rogue 23 neutral character",
  "HDDvD1Q1JyMm4ZdRvqa+twyYXdYKsBHHU0STWTzslJwpPREw7CM0J0Gj+0CaI/1l": "arcane protection wizard dodge token spell range 1 upgrade",
  "hZvzFy0lN4zKqJNGb3SCxo5L49uHcXJ0+cwOnTv+H6tWtISUvn/Bff0GqwdxJ8Ex": "mirror image illusion range spell 2 upgrade",
  "pYzGYE2AJlsc05fwHHTp3GidNnRV+ymPxRWemQeJywuCaISm6phSyojuFidj7j8D": "cosmic essence two uses tactic 1 upgrade",
  "QIO525aUQjFAg4yOJBy0Gygxl2pnZBFJgELLoZKuNTcSrMCLYXERY1MgQIWgQGL2": "spellbook witch wizard focus 1 upgrade",
  "to3KQuHOxJKWryZdlVMcKNOnlJSZfVLNV8C080I1lL7e4yhMolUGpRZSWIWIuUgx": "combat superiority fighter bonus die 3 upgrade",
  "2KoedQ2gkrOXdWRjrsHRxNFoQWbmmhnkp6U/oGnlOiXYYuQ7umihwtkPCtvleJ6j": "smoke bomb rogue range single use 2 upgrade",
  "0HeWmsbO3YJmJlaw8LG1s2sDIycXaFjQMFioqNSeZusKBgpCFMAfTzxK5t2LVyyT": "gnome battlesmith range dire dodge knight smith 23 advocate character",
  "9VhLT8F3XEJPGrjJupiQUnLHr5BOPpk9tIT01kQTUzt4S1tS169h2Gpk2bws7OCo": "magic ring dodge 1 upgrade",
  "SECE8OSSehoR8RHhnNYxUaGoqPoZ+Yx/K9Q0dbE45FbGBjawUrKwvY2FjC2NQE9k": "mounted battlesmith range dire small rider knight smith 13 advocate character",
  "MtFV4vX+CXNatx4869CsRV01qu6NSsDrwCQhEQEY+ElDRWMHZo0RDfTBpNMhseNH": "ibex small mount rider climb push beast 10 advocate character",
  "CrtPTX7BNFRW97tQqNGjZEt+490KJNG5jl5eLols1YOH8+bkW+Qs47aLSkrw6sUQ": "hell hound berserker deadly damage bonus barbarian beast 23 advocate character",
  "K0WqxITMRZVdYr/sQAPz+0btUKD+7cgVQmw6PIp7h55zYKubsjvGwZlCnkD3V6Bj": "",
  "BiE5I434jyiYgtSwsb51cpFKhZpTIGDxzErF6VpsjjGJPl+p8ojU7tOousaAnNF9": "vermin mouth bonus damage pig 20 adversary character",
  "T5uHBEb50ATzg62ECtrsSNR7HIzCtE/24h+HHfVcyb0Bs+Hk5IzSpCabkaD57EIS": "rat swarm Vermin Mouth summon dire recover adversary",
  "HBIRysVa5cWeYvOEqRvC0FhTh95gyaN28GIyPjvzVRyO6mZmJi8t2TYdWKZZg1Zy": "Ogre ratarius range dodge recover fighter 26 character adversary",
  "0r90XIzMpGBgFjRgYyMzKRlp6B1NR0vl5aWjr/49/TMzhrNjOT/lHIWjwjg5wuha": "veteran's edge reroll tactic 1 upgrade",
  "RuUQH1WlQS0RlZ/yGrriXAUKiViFx/AUf33Hju3vpb7kmtmuFo+3IdqJUOWCTthU": "iguan assassin range dodge recover rogue 23 adversary character",
  "x68CpBQ+E0JNJI/abMXEIL5OVm4NaVX9jvkweEHF4lUq9KBU+0aVAFT9OyceF6LB": "neurotoxin rogue dagger poison 2 upgrade",
  "NKrWYgUWt0CAoJZ2BhsNDqYQ2NgDEoGBqdjo+j48+lnG5qPv2cLvXkXFrxv3+Mo7": "Flame bearer range stun beam move wizard 26 advocate character",
  "8joZ+J6lLCi6OzC5ycXZEQ8wTfLl+MqVOmISUtHeMHN0PzxuXh6eMnX2U3SsRKXU": "Elemental smite witch wizard two uses stun range spell 2 upgrade",
  "zRT6Gh0NHTL9YU6NqlM9xPnlIc++ThPdSoladlTJ86CTt37ICjY1mYmBjj+XMPRE": "Lone Guard Commander Dodge Range Warlord Shield fighter 30 advocate character",
  "wheKrNK8j2DoSTJ805JXRUGgocdZZB5Ejxv77+gX+PZ5inz6U0eL6PDxPVSE+35X": "champion tactic 2 upgrade",
  "EJnbKwbcNK9BkwjJXi+ClDULZyJVGHolX8RvzYqfl/UWhI6SOLbORb0Pf7li9Ex/": "bounty hunter range dodge scout fighter 23 advocate character",
  "evARtbWlRNFrH5iGbQ/MjKwuH9+zBh/ERc+P0iAoP8MHLaWG4PKfjli1Zj9869Ly": "combat mobility dodge token move 1 upgrade",
  "zGZwP7YfmK1f98I/6hO44bMwaz587NdzfaGESouwg+VMZx2nyWL/sZAz8b/A89/f": "Bone fury range move wounded bone beast flying climb jump 16 adversary character",
  "7RQpTYB4IAQ74lEMzwPukwb75X0eIlkJaeBg8vbwE/n4BgJCXEIykmCh9OmYTYuH": "Bloodthirsty beast barbarian ad charge 1 upgrade",
  "h++QKatWjBphC1nUAwLj5rfgQJpZmZGcqW+gpzZs9EyXKVJSmazdf+ycOcc8G/6Y": "berserker pig ad barbarian pig 16 adversary character",
  "SWzL4ZQJbGriOntObNys5BSkYWbKwtkZkpYtCks2hZpwLe7Nge23buwe9nhTsjYv": "pig out destroy recover health 1 upgrade",
  "lZIdCUcI6aznZoWNsNbk420NfXZ1MhMycbwe8icftxMELjUjifQzXAhe5t9pTxWL": "warden of justice recover health knight holy 23 advocate character",
  "KrREl4Fy/O5iPhhYKcqICdSsluWUsWgaG5uHr2CvxLFmewlL4jTyDFrtDm7uDkgM": "gnome grenadier range stun dire place scout 23 advocate character",
  "LYC4C1mIMdPgSHoEf3bth/4CCePX2C8hUqKp5VtXIFeN1/yODsoP79sH3nLmxcsw": "lone guard infiltrator range bind disengage dodge rogue 23 advocate character",
  "2fRaNMfhcnd6/hiENqCbFR2LZzD5ZsP5UFCOgepOeoXDIfalUuhTJFcsPayooXfn": "wild elf witch range place reroll nature witch 26 character advocate",
  "ycHGnnmu3LEBEZIeD91Re7MPX56bilcwe8MuMlG4/bqzsU8c/8C7ltOYY1gUv5P1": "",
  "8K5iFszipMu3k6PnjnQ+sd7nl4GgaNGIiH75mLxc+8hAaN6uPtj1/H+m824ZJzL5": "",
  "zqTnpyIpLio8RXgihKW/m5y9ewaP1uxCenm/f0dHfH8iWL0L5rd9y6eAorv5+C0b": "dark prophet range poison damage wizard bone darkness 26 character adversary",
  "BKeCzzHklxsUjPSEdcXBz8Xr7B1iPnEBYteAk6KNBr59aNaNy8NQL8HmLPqjmYsH": "destroyer pig reroll fighter pig 20 adversary character",
  "SSn22g1MfEsaMx68f5uHBwO14E3MfPG/dwhqo8Zft1aobalcurJ6yoviQCr4jv0F": "iguanan marauder range shield armor fighter 23 adversary character",
  "8vXuHgvMX4pWRxxMfHIzIiArHR8VlVHTOgWYeG6DGoP6x11uz0xT4iZipYUbAfFE": "Slayer Squid range deep rogue dodge bonus die 23 adversary character",
  "s3Y+oz06TP9vy4GxfPX8Q9ve8TFzc4OAjrdq5ESGiIKO8vP9+L6c/PxK2d2uPlWS": "",
  "opM59Gt6MOlw46t/+F2PLjFjm37M1FqN+wviy+xx98GjNfmCWf59fJwz0P3wECqF": "",
  "ZJGNK3O9q1bY2mLVoiMSUdoRGR4u6GR8ZK9kCZnrWFUz4X2Hg2QSFhYuF/3bsT01": "alchemical munitions damage bonus ranged 4 upgrade",
  "8cJ1rGo5ftx8aDV8jSeKZzPfRqVdk7N5fycQxKjlq6H/vSfH5TYlw0una8Gs0a1E": "bastion shield armor dodge 3 upgrade",
  "kFagQ0DOvUeT4wWSvSfXaHeBHL71qLol1C+h6JgAmPJdakuBUUcmcX2ZWiczaQpV": "blade oil single use difficulty tactic 1 upgrade",
  "RVVkrEJ12pNDno7pXoXVdl0hpPjZgqNHU9PeDh7g4vL094eat4I8UhAWt++V3FYh": "cloak of concealment armor ranged 2 upgrade",
  "w2zRtg0L8eQa1a1ZmjKLSUoMeA4chMSZKQtHaLVU0KvRe5NEcPH8L6H9fhlw2bUG": "corrosive vial single use armor range tactic 1 upgrade",
  "Ske8t/NSlqyT2DPfsPGEpmw1N1dsIDQ2/F8BHD5XvsoEkvTMOOPfvx3LMTMXrMI/": "cyclone witch single use move place 3 spell upgrade",
  "1h9BJ+QC9e5knUe8kNVQ2FynrVaESssYSPWUGpHAuOcCjFIyFLRfaokDGPjiKGxa": "quicksilver bangles move charge 2 upgrade tactic",
  "1btsLOGie9pnhOv16dceuNg9G2bSvhKKpr6zHo5hEozstWIWnjFuuaFD4XXZrtW7": "gauntlets of strength push move 1 upgrade",
  "SG2MhoUJ7AMtdAEXv0EYeiS+KU+4SjAsmFJ92KfH8RE6Jc43KuWswNgWJaYBUnFS": "Heavy armor fighter knight armor 4 upgrade",
  "jJNvLLKmlpbueyKUF+9cxBrrtqOopdRxFmy2RQjD5KchVWvnmWK5bWc/BwO7qnkF": "healing herb single use recover health tactic 1 upgrade",
  "B4js2uhyhQykckhUHJZBKaZUSlXBmuhSHFrZSB6BIzbyHjVwQiOekgspxDscyhkK": "inner mastery difficulty 1 upgrade",
  "fwrRDKAHP+/AV8umg5HqYJ/oHe08PFCe4eboisEoFnGjRC3YaNUSUyCmHh4XBydU": "magic lantern bonus die 1 upgrade tactic",
  "RbkZ8vYkKUa1zOVaO5IVBMC6zipELlFlZubQqa0mIxjMBp6t4Vk++1JDVetcXqzX": "noxious bomb single use dodge token range 1 upgrade",
  "sbgmKGsIqTCrXCUQEs8Q5iVTi6B9pK0TNVJ5hVT24TY0LFhBQnokPUjkSmQeCqcK": "rebuke holy bind range 1 upgrade",
  "C/XbuRfIeNhq+fAquEuWbkzjWlVmELKWlJKKdaAHUE+nnhkS6t0TQ2Gq7uXnD19I": "ruthlessness darkness deep damage range 2 upgrade tactic",
  "OB1aDQaAFGLcemrLxIsKWjPf6U0oiKjkN4WJTHPRe30DL4rEtLd9QMorOqyKPZ+f": "shadowglass dagger dire bonus die 4 upgrade",
  "lW7SZZn8ZwE2be+MESffHxEtCQBSrkol7HRg74/LERIQJYysd4yVy4h8PF6jEuVl": "war paint fighter barbarian charge 2 upgrade",
  "00YaFBuPPma9GrRzfExMRi565duGLCHbIOKspKEWBnHgw5JX/YbFwrfigvLcH+/f": "wildland accuracy ranged cover 2 upgrade",
  "DOjwuwesuOV9IPdSOvDjQAnDu8HVUrBmDvgYOwtdVGP5JbMjkpCVGRkfhp/g+Y99": "sword of fire relic",
  "pT9L2x72PRV0sQVE5E75LvxmDX1o3o0ac/Bj/XFS0a1uHPI6rXw/Y9BzB2xkcP/A": "axe of cold relic",
  "UqiLb1/3uOR+TancrmQLASV879WrC//2MUeP/mOes8aI2RWX/o6Ak4fvI0zKwFsz": "Death strike war maul relic",
  "yv+ev7H6PAu5dPWOdBc4zM+t+NHIdjJ07Byl6Y7cmEu3XzRoyZMgu/TB4EW1tbXn": "the ancient skull relic",
  "dnHN6zHV9Pm4XpM2aiTMWqylvMnjIBk7+dz8FGK2aOhLFGg+IVayI4NBwz5v2AX3": "the music of life relic",
  "fvJJeM5HgU5GZQQgqEYmrEFYklEPKFiLSUYVKsD8rLDNibyUGOezPoiF/M6teuqi": "helm of legend relic",
  "jV9s9kpd+ybgtefe516eOnXnoS3ft0lT557okXcfjgEQQFB2HllqUCvLyPR+4fC1": "",
  "pHxpimu3ftwWUDR8Pv82HCpGvw1CPPWM9bvHY+GjVuiF82b8El/YfL5xcPH4Jb75": "",
  "Ub+yItKR4Htm/Aij9WIyj45Z88LlKqqvm4Y3S/Tpz8xOocB3xRko+S0s8JZjrsI2": "questing knight range ad knight 23 advocate character",
  "Jt23ewugSJromXLiGiUdTfXlqJpryNvYXakdQ42kpLSnD1ahraRLdTricMsSboHB": "thief range dodge token steal rogue 20 character advocate",
  "JRGJugIJ/IXcKTQZ8J4DCCqVKSFBg0zHD30VNcvnmPeR4vXoUjW53Lg0VELXc3V5": "cleric of justice summon cleric holy 23 advocate character",
  "FIZmVStzp1aIfff98AB0enkixeIouOEDP/F/honDx+DIsWLuCANxs7O/Z8zEhPg4": "spirit weapon cleric of justice upkeep",
  "6GSUmsUrCN62GsJAWSzpIZKjkVmqw1Ak8woYVj7tVEyUzIXSUDAj5enpKNagI7hi": "hammer of justice cleric difficulty summon upkeep 4 upgrade",
  "kbtMj1c6mARbgaYq70rpIATpE1ys8ic2w0S4L4MOY0dAS8ziQRCU/KdTGAhkQPye": "healing prayer holy two uses recover health spell range 3 upgrade",
  "G1UKJrq7erVF+MvOwsxMTEYPHCBdixez97LT2cnOBgbcOhEmQCxd/Hy/MoOaXva2": "sigil of justice cleric armor critically 2 upgrade",
  "G0eBQy01JE3AzFK5H2QYmbej1MOdm4fOkyDh06iGPHT+L8hQtISU1D0agoVKnbEI": "writ of justice knight cleric single use destroy 1 upgrade tactic",
  "Byc3VBBECoqSkoxJULCVj91RLs273PiTCyReNio9GpY1t0aHc7YmJiJBDQut0dYk": "reposte knight dodge tactic 3 upgrade",
  "ZmpkhOSYWNtSXaNKuLmrWr8r3QLNA40LFz33EEn7rwaUCjd/fOmDxuBLKyRbot7n": "sword master knight bonus ad tactic 2 upgrade",
  "zs4eTqAnsnJ9hLvVEWhVJXrsX9u/c1opFI4soRYZgwejhKlCjBC2dk5HMMHTUeQc": "dive attack rogue damage 1 upgrade",
  "CFLQkNgCUC/dGmZVO0atEEAQGBuHbjFho1b82LaVpKorSNtVhSBP40V2gxvXblCo": "nimble armor rogue 2 upgrade",
  "IykJlJ/6YjIz2D/yY+z+RzuCaDTXbBcXCGqIHQrkbkw9P7KNpPuESCuSfg4ENZnF": "distraction range rogue armor 2 upgrade tactic",
  "ZYvnwF6td3RcClY/hr+zYcvXwbiaklO7qmujpmjuyJrPQUZOfm4kVEAq48CIFr4+": "billman range dodge companion 10 advocate character",
  "4If/8KBkZmLPLHJ6chGwpo6eohIyML5qamcC7iguIly+TTkUn1CA4Owppfl+G33z": "lone guard ranger range bound nature scout 21 advocate character",
  "eOR0ZOHhQVFDi+hUjiAQMHICE2FsdOnsbr0NewtLHjsbQ0M0VKWgZW/7AMK9asRV": "lone guard warrior stun recover shield fighter 23 advocate character",
  "Dl4iXW0UniWVhacI4GQTD5oEzVGeNHMnOQmzMuOhK7Dx7F0Ut3uMiOrkfE1d4alc": "sabertooth bind beast companion 5 advocate character",
  "06NaogNKgcrt+6i3pNW6NCSEWkJsbL/WxlHJCbRz+TkhJx89ZtXLt+A8eOHMbxU2": "bold advance fighter move tactic 2 upgrade",
  "O3wwe+IGg0aISxM2ZpVZwKZ7Xwox70/7ovGKsXzNdy3QPze6B/h8acg2BobAJzK1": "indomitable guard fighter dodge token 1 upgrade",
  "mxiSFHQgztmHZWHAU5EZ/PhtIyr2hdCBQN9UFEmLXR0rHcn0pXldI2oK2Voj4Cql": "outflank scout deploy 1 upgrade tactic",
  "7rFGUga0N8QlOBoOQuxW3Q7xLv3rmqEHvWrjQ+khMQPI36hCzmeocJ14OPMtfF+p": "quickshot tactic range 2 upgrade",
  "t0tJ5985DWLUN0Ir4LPZM0kw8fPPLngcaIEf0wa+Y4QXSvWCjqtLKR+aBs2JLSWj": "spear trap scout bind 2 upgrade tactic",
  "9K0Q3+jEoAGCuQqiVXMw4J0aHQqOOQTpNIigbHL95FySLuiIpTsyVuYa6CnY0lgx": "hand axe upgrade 1",
  "xKSwszVKtSCR07dkTLr76Gt48vLK2s+T6njh7EsOEj8OqN0DrcnBxYmCWkFlYVif": "iguanan poacher range deadly bound scout 23 character adversary",
  "jhp2m80dDh4lIEO7ZuQaWq1VjVJWI8MTERnTt1RPD9ByhXpjQOHjwIb1+//5N99l": "iguanan slaver range bind poison reroll fighter 23 character adversary",
  "J8UKVsCUSGBiI4wAfk6SAUNpqMeJCSgWu37+H81TjcTUkvNKH0rq5o0bQxFixcCB": "iguanan witch range dire difficulty deep 26 character adversary",
  "GmBzCgby/s+mM/97VBvXpQKvUQGRWNh48eM3jrde4MGjRqwnPggtc5DHZ350W5ds": "mangrove basilisk range bind poison beast 20 character adversary",
  "QqnpVJTD6emBwia9HCzAx2ttYoKDZGAQlsmGzUmNGalZ4HoGq/MqumJlyx8UzXVp": "acid shot sling and stone two uses bonus damage 2 upgrade tactic",
  "xpskvdQoeRZ0G7kiycVJ50PprkPGAkrQOnS6X0lzxpKQQggo1umnUdEvPNt8LpTn": "apex predator beast bone recover disable 1 upgrade",
  "GdnQsbGwu0b9Uc/fr1QU52Nrr1HoJAb08E+Pni+v1HuBfxhqInAd6eCAsV7omUXE": "blood poisoning witch recovery range spell 2 upgrade",
  "C4uAmX8MKeI8hMO3VbXf4vuSct+na1C4jIZ5YVlTSx6b+i0xeQl3bSgp6tk6Jx//": "neolithic effigy armor magic 2 upgrade",
  "wrA2trChAUR1pqCp5FR+HCmePo0qouLDRqr9kLks6bHoDDuM0tYLCgpDplTqoMUl": "sludge mire witch spell range 2 upgrade",
  "4whcV10CLQs2lCdKirOo2KoqP/5qDvuNufsjT6njcBBBp1xaWoOF4QmM3lyVKKiu": "dart trap tactic poison deadly 2 upgrade",
  "GDUaFiJTi4eSL280f4+9xEaEgwXr8PRcC7jwgOi0ZCCsVSfIla0+SZGxuicYO66N": "",
  "iLinHQQEWdowoF38Ls2GehsR4yXQQYkB+KxkKLaNPCFWhkCO9qpoEEGc2XIhQAzS": "",
  "9l7j8iVvqiPSz21g38+sNBnDp1Es4mR9SoWQtu7u5IyQTOXriMPZ9tw+Ejv+P0mX": "",
  "iSgMbWuMamNAQhCbSFZS/iFeQLi/eW4KnYiu/UWehtTf5ZxgnYclAZE3UbmbZk8N": "",
  "gEKio9OHniOA4e+gOHj5+Wewmx21BWXiku12Gd22P8kIEoKatEdlahlmV8+PjHNf": ""
}